<?php
    header("Cache-Control: no-store");
    //https://unicab.org/registro/docenteunicab/carnets/cupon_coesco2.php
    
    include '../updreg/mpdf8/vendor/autoload.php';
    
    $mpdf = new \Mpdf\Mpdf(["format" => "Letter", "margin_left" => 10, "margin_right" => 10, "margin_top" => 5, "margin_bottom" => 0]);
	//$mpdf->SetDisplayMode('real');
    
    $content = '<!DOCTYPE HTML>';
	$content .= '<html>';
    $content .= '<head>';
    //$content .= '<link href="../../bootstrap532/css/bootstrap.css" rel="stylesheet" type="text/css" />';
    $content .= '<style>';
		//$content .= '#divcontenido {display: flex; justify-content: space-around;}';
		//$content .= '#divizq {width: 30%;}';
		//$content .= '#divder {width: 60%;}';
		$content .= 'table {border: 1px dotted black; border-collapse: collapse; width: 90%;}';
		$content .= '.thtransp, .tdtransp {color: white;}';
		$content .= '.negrilla {font-weight: bold;}';
		$content .= '.rowtransp {color: white;}';
		$content .= '.fontmedio {font-size: 18px;}';
		$content .= '.centrar {text-align: center;}';
		$content .= '.bt {border-top: 1px solid black;}';
		$content .= '.espacio {border-left: 1px dotted black; border-right: 1px dotted black;}';
		$content .= '.sinbordeshorizontales {border-top: 1px dotted white; border-bottom: 1px dotted white;}';
    $content .= '</style>';
	$content .= '<script src="../../js/jquery-3.7.1.min.js"></script>';
	//$content .= '<script src="../../bootstrap532/js/bootstrap.js"> </script>';
	$content .= '</head><body>';
	
    $content1 = '';
	$content1 .= '<br><div id="divContenedor">';
		$content1 .= '<table id="tblFinal">';
			$content1 .= '<thead>';
				$content1 .= '<tr>';
					$content1 .= '<th class="thtransp">1</th>';
					$content1 .= '<th class="thtransp">Fecha_generación</th>';
					$content1 .= '<th class="thtransp">Fecha_generación</th>';
					$content1 .= '<th class="thtransp">Cupón No.</th>';
					$content1 .= '<th class="thtransp">5</th>';
					$content1 .= '<th class="thtransp espacio sinbordeshorizontales">E</th>';
					$content1 .= '<th class="thtransp">7</th>';
					$content1 .= '<th class="thtransp">Consecutivo</th>';
					$content1 .= '<th class="thtransp">Consecutivo</th>';
					$content1 .= '<th class="thtransp">Consecutivo</th>';
					$content1 .= '<th class="thtransp">NIT:</th>';
					$content1 .= '<th class="thtransp">Fecha_generación</th>';
					$content1 .= '<th class="thtransp">Consecutivo</th>';
					$content1 .= '<th class="thtransp">Consecutivo</th>';
					$content1 .= '<th class="thtransp">15</th>';
				$content1 .= '</tr>';
			$content1 .= '</thead>';
			
			$content1 .= '<tbody>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Consecutivo:</td>';
					$content1 .= '<td>CONSIZQ</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Consecutivo:</td>';
					$content1 .= '<td>CONSDER</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">No. Cupón:</td>';
					$content1 .= '<td colspan="2">NCUPONDER</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">No. Cupón:</td>';
					$content1 .= '<td>NCUPONIZQ</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3" rowspan="3" style="background: transparent;"><img src="../../../assets/img/ghf/logo_Coesco.png" width="300px"/></td>';
					//$content1 .= '<td>CONSDER</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Cliente:</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					//$content1 .= '<td colspan="3" rowspan="3" style="background: green;"></td>';
					//$content1 .= '<td>CONSDER</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3">CLIDER</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Fecha generación:</td>';
					$content1 .= '<td>FECHAIZQ</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					//$content1 .= '<td colspan="3" rowspan="3" style="background: green;"></td>';
					//$content1 .= '<td>CONSDER</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">NIT:</td>';
					$content1 .= '<td colspan="2">NITDER</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Cliente:</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3" style="color: red;"><small>COESCO Colombia S.A.S. NIT 901300741-5<small></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Fecha generación:</td>';
					$content1 .= '<td colspan="2">FECHADER</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3">CLIIZQ</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">NIT:</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3">NITIZQ</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla fontmedio centrar">Valor:</td>';
					$content1 .= '<td colspan="2" class="fontmedio centrar">VALIZQ</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3" class="centrar bt">ESTACIÓN DE SERVICIO FIRMA Y SELLO</td>';
					//$content1 .= '<td>CONSDER</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3" class="centrar bt">CLIENTE FIRMA Y SELLO</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr class="rowtransp">';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3" rowspan="4"><center><img src="../../../assets/img/ghf/cb.png" width="270px"/></center></td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td colspan="3" rowspan="4"><center><img src="../../../assets/img/ghf/cb.png" width="270px"/></center></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					//$content1 .= '<td class="negrilla">Consecutivo:</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla fontmedio centrar">Valor:</td>';
					$content1 .= '<td colspan="3" class="fontmedio centrar">VALDER</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					//$content1 .= '<td class="negrilla">Consecutivo:</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					//$content1 .= '<td class="negrilla">Consecutivo:</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="2" class="negrilla">Condiciones de uso:</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="7">* Válido únicamente para consumo de combustible.</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="7">* Este cupón será redimible al portador en las Estaciones de Servicios COESCO autorizadas.</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="7">* Es responsabilidad del beneficiario de este cupón del manejo y uso del mismo.</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="7">* No será valido si tiene enmendaduras y tachones.</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="7">* Este bono no puede ser redimiendo total o parcial en efectivo..</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio sinbordeshorizontales">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
			$content1 .= '</tbody>';
		$content1 .= '</table>';
	$content1 .= '</div>';
	
	//********************************************************************************************************************************
	$content1 .= '<br><div id="divContenedor">';
		$content1 .= '<table id="tblFinal">';
			$content1 .= '<thead>';
				$content1 .= '<tr>';
					$content1 .= '<th class="thtransp">1</th>';
					$content1 .= '<th class="thtransp">Fecha_generación</th>';
					$content1 .= '<th class="thtransp">Fecha_generación</th>';
					$content1 .= '<th class="thtransp">Cupón No.</th>';
					$content1 .= '<th class="thtransp">5</th>';
					$content1 .= '<th class="thtransp espacio sinbordeshorizontales">E</th>';
					$content1 .= '<th class="thtransp">7</th>';
					$content1 .= '<th class="thtransp">Consecutivo</th>';
					$content1 .= '<th class="thtransp">Consecutivo</th>';
					$content1 .= '<th class="thtransp">Consecutivo</th>';
					$content1 .= '<th class="thtransp">NIT:</th>';
					$content1 .= '<th class="thtransp">Fecha_generación</th>';
					$content1 .= '<th class="thtransp">Consecutivo</th>';
					$content1 .= '<th class="thtransp">Consecutivo</th>';
					$content1 .= '<th class="thtransp">15</th>';
				$content1 .= '</tr>';
			$content1 .= '</thead>';
			
			$content1 .= '<tbody>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Consecutivo:</td>';
					$content1 .= '<td>CONSIZQ2</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Consecutivo:</td>';
					$content1 .= '<td>CONSDER2</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">No. Cupón:</td>';
					$content1 .= '<td colspan="2">NCUPONDER2</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">No. Cupón:</td>';
					$content1 .= '<td>NCUPONIZQ2</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3" rowspan="3" style="background: transparent;"><img src="../../../assets/img/ghf/logo_Coesco.png" width="300px"/></td>';
					//$content1 .= '<td>CONSDER</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Cliente:</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					//$content1 .= '<td colspan="3" rowspan="3" style="background: green;"></td>';
					//$content1 .= '<td>CONSDER</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3">CLIDER2</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Fecha generación:</td>';
					$content1 .= '<td>FECHAIZQ2</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					//$content1 .= '<td colspan="3" rowspan="3" style="background: green;"></td>';
					//$content1 .= '<td>CONSDER</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">NIT:</td>';
					$content1 .= '<td colspan="2">NITDER2</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Cliente:</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3" style="color: red;"><small>COESCO Colombia S.A.S. NIT 901300741-5<small></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">Fecha generación:</td>';
					$content1 .= '<td colspan="2">FECHADER2</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3">CLIIZQ2</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla">NIT:</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3">NITIZQ2</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td colspan="2" class="tdtransp">XXXXX</td>';
					//$content1 .= '<td>8</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla fontmedio centrar">Valor:</td>';
					$content1 .= '<td colspan="2" class="fontmedio centrar">VALIZQ2</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3" class="centrar bt">ESTACIÓN DE SERVICIO FIRMA Y SELLO</td>';
					//$content1 .= '<td>CONSDER</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3" class="centrar bt">CLIENTE FIRMA Y SELLO</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr class="rowtransp">';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="3" rowspan="4"><center><img src="../../../assets/img/ghf/cb.png" width="270px"/></center></td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp"></td>';
					$content1 .= '<td colspan="3" rowspan="4"><center><img src="../../../assets/img/ghf/cb.png" width="270px"/></center></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					//$content1 .= '<td class="negrilla">Consecutivo:</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="negrilla fontmedio centrar">Valor:</td>';
					$content1 .= '<td colspan="3" class="fontmedio centrar">VALDER2</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					//$content1 .= '<td class="negrilla">Consecutivo:</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					//$content1 .= '<td class="negrilla">Consecutivo:</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="2" class="negrilla">Condiciones de uso:</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="7">* Válido únicamente para consumo de combustible.</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="7">* Este cupón será redimible al portador en las Estaciones de Servicios COESCO autorizadas.</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="7">* Es responsabilidad del beneficiario de este cupón del manejo y uso del mismo.</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="7">* No será valido si tiene enmendaduras y tachones.</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td colspan="7">* Este bono no puede ser redimiendo total o parcial en efectivo..</td>';
					//$content1 .= '<td>XXXXXXX</td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					//$content1 .= '<td></td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
				$content1 .= '<tr>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp espacio sinbordeshorizontales">E</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td class="tdtransp">XXXXX</td>';
					$content1 .= '<td></td>';
				$content1 .= '</tr>';
			$content1 .= '</tbody>';
		$content1 .= '</table>';
	$content1 .= '</div>';
	
	$content1 .= '</body></html>';
    
    echo $content;
    echo $content1;
	
	$folder0 = '/carnets/';
    $folder = __DIR__.$folder0;
    
    $mpdf->WriteHTML($content.$content1);
    
	echo $folder.'Cupon2.pdf';
	$mpdf->Output('Cupon2.pdf', 'F');

    	
?>
